<a href="https://colab.research.google.com/github/SterMoum/Bash-Scripting/blob/main/Notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#get tensor back at python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor = torch.tensor([[[1,2],
                        [2,3],
                        [1,2]]])
tensor.shape

torch.Size([1, 3, 2])

In [ ]:
#Random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3821, 0.8151, 0.2147, 0.7752],
        [0.5368, 0.5344, 0.3554, 0.2658],
        [0.4648, 0.8048, 0.1436, 0.8146]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor1 = torch.rand(3,4)
random_tensor1.shape

torch.Size([3, 4])

In [ ]:
#Zeros and Ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#Create a range of tensors and tensors-like
one_to_ten = torch.arange(start=1, end=100, step=10)
one_to_ten

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Creating tensors like
ten_zeros = torch.ones_like(one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**NOTE:** Tensor datatypes is one of thje 3 bif error you ll run into with pytorch and deep learning
1. Tensors not right datatype -> 'tensor.dtype'
2. Tensors not right shape -> 'tensor.shape'
3. Tensors not on the right devide -> 'tensor.device'

In [ ]:
#Tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 2.0],
                      dtype=None, #What datatype is the tensor(float 32 or float16)
                      device=None, #What devide is your tensor on
                      requires_grad=False) #wheter or not to track gradients with tensors operations
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) #Or half
float_16_tensor.dtype

torch.float16

In [ ]:
uint_8_tensor = float_32_tensor.type(torch.uint8)
uint_8_tensor * float_32_tensor

tensor([ 9., 36.,  4.])

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36.,  4.])

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1908, 0.7014, 0.7694, 0.4559],
        [0.6502, 0.7794, 0.9282, 0.3355],
        [0.6950, 0.2142, 0.2670, 0.1838]])

In [ ]:
print(some_tensor)
print(f"Datatype of Tensor:  {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1908, 0.7014, 0.7694, 0.4559],
        [0.6502, 0.7794, 0.9282, 0.3355],
        [0.6950, 0.2142, 0.2670, 0.1838]])
Datatype of Tensor:  torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
#Element Matrix Multiplication
tensor1 = torch.tensor([[1,2],
                        [1,2],
                        [1,2]]) # 3x1
tensor2 = torch.tensor([[3,4,1,2,3],
                        [3,4,5,3,2] ]) # 2x5

In [ ]:
#Matrix Multiplication
torch.matmul(tensor1, tensor2)

tensor([[ 9, 12, 11,  8,  7],
        [ 9, 12, 11,  8,  7],
        [ 9, 12, 11,  8,  7]])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]]) #3x2

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]]) #3x2

#torch.mm(tensor_A, tensor_B) #same as torch.matmul

In [ ]:
#Transpose the tensor_B using tensor_B.T in order to make it 2x3
tensor_B = tensor_B.T
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#Finding the min, max , mean, sum etc (Tensor aggregation)
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
#find the positional min and max
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [ ]:
#Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze() - removes all single dimension of target tensor
x_reshaped, x_reshaped.shape,x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor
x_reshaped, x_reshaped.shape,x_reshaped.unsqueeze(1),x_reshaped.unsqueeze(1).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([1, 1, 9]))

In [ ]:
# torch.permute() - rearranges the dimensions
x_original = torch.rand(size=(224,224,3))# [height, width, colour channels]

#permute the original tensor to rearragne the axis order
x_permuted = x_original.permute(2,0,1) # shifts axis=0->1, 1->2,2->0

print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
#Indexing (selecting data from tensors) same as numpy


In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
#You can also use ':' to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
print(x[0][2][2])
#index on x to return 3, 6 ,9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [ ]:
# Pytorch and Numpy
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Change of the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Reproducability (trying to take random out of random)

#Create 2 random tensors
tensor_a = torch.rand(3, 4)
tensor_b = torch.rand(3, 4)
tensor_a, tensor_b, tensor_a == tensor_b

(tensor([[0.2420, 0.1852, 0.1345, 0.9169],
         [0.1346, 0.2424, 0.4302, 0.0223],
         [0.5432, 0.6409, 0.3899, 0.8768]]),
 tensor([[0.2762, 0.6236, 0.3619, 0.9829],
         [0.5463, 0.3561, 0.3107, 0.0103],
         [0.0306, 0.1311, 0.8079, 0.9062]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
#make some reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(3, 4)


tensor_c,tensor_d,tensor_c == tensor_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
#Running tensors and pytorch objects on the GPUs

import torch
torch.cuda.is_available() #Cuda is nvidia's API that allows us to use GPUs for numerical computing

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

In [ ]:
# putting tensors and models to the gpu

tensor_cpu = torch.tensor([1,2,3])

tensor_gpu = tensor_cpu.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#if tensor is on gpu, cant transform to numpy
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
torch.mm(tensor_cpu, tensor_gpu)

RuntimeError: ignored